Repository cloud-native-toolkit/terraform-ibm-vpc-vsi, pull requests merged in 2021-05, with the labels that each got.

#1 Updates test variables
  .github/scripts/validate-deploy.sh
  .github/workflows/verify.yaml
  main.tf
  module.yaml
  outputs.tf
  provider.tf
  scripts/init-script-ubuntu.sh
  test/stages/stage1-hpvs.tf
  test/stages/stage1-resource-group.tf
  test/stages/stage1-subnets.tf
  test/stages/stage1-vpc-ssh.tf
  test/stages/stage1-vpc.tf
  test/stages/stage2-vsi.tf
  test/stages/variables.tf
  variables.tf
Labels: feature, major

#4 added flow log for vsi
  .gitignore
  README.md
  main.tf
  test/stages/stage0.tf
  test/stages/stage1-cos.tf
  test/stages/stage2-vsi.tf
  variables.tf
Labels: feature, minor

#5 Adds support for encrypting boot volume
  .github/workflows/verify.yaml
  main.tf
  outputs.tf
  test/stages/stage1-cos.tf
  test/stages/stage1-hpcs-key.tf
  test/stages/stage1-hpcs-resource-group.tf
  test/stages/stage1-hpcs.tf
  test/stages/stage2-vsi.tf
  test/stages/variables.tf
  variables.tf
Labels: feature, minor

#6 Uncomment encryption value after block storage auth added
  main.tf
Labels: bug, patch

#7 Exposes variable to set security group rules
  main.tf
  variables.tf
Labels: bug, feature

#8 Outputs primary_network_interface.id values
  outputs.tf
Labels: feature, minor

#9 Adds dependency on cos_bucket for flow_log_cos_bucket_name
  module.yaml
  test/stages/stage1-cos.tf
  test/stages/variables.tf
Labels: chore, patch

#10 Adds kms_key dependency to metadata
  module.yaml
Labels: chore, patch

#11 Adds warning message if using a deprecated image
  main.tf
  scripts/check-image.sh
Labels: feature, patch

#12 Adds logic to fail if image is deprecated and flag is set
  main.tf
  scripts/check-image.sh
  test/stages/stage2-vsi.tf
  test/stages/variables.tf
  variables.tf
Labels: feature, minor

#14 Moves flow-log logic and variables to separate module
  main.tf
  module.yaml
  variables.tf
Labels: enhancement, minor

#15 Collapses security group rule creation into a single resource
  main.tf
Labels: chore, patch

#17 Adds base_resource_group input from vpc output
  main.tf
  module.yaml
  test/stages/stage1-subnets.tf
  test/stages/stage2-vsi.tf
  variables.tf
Labels: feature, minor
